<?php

namespace Behat\Mink\Selector;

/*
 * This file is part of the Behat\Mink.
 * (c) Konstantin Kudryashov <ever.zet@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Exact match selector engine. Like the Named selector engine but ignores partial matches.
 */
class ExactSelector extends AbstractNamedSelector
{
    // These xpaths were generated by modifying PartialSelector's $selectors
    // property using this regular expression:
    // @code s/contains\(([^\(\),]+), %locator%\)/$1 = %locator%/
    protected $selectors = array(
        'fieldset' => <<<XPATH
.//fieldset[(./@id = %locator% or .//legend[normalize-space(string(.)) = %locator%])]
XPATH
        ,'field' => <<<XPATH
.//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')][(((./@id = %locator% or ./@name = %locator%) or ./@id = //label[normalize-space(string(.)) = %locator%]/@for) or ./@placeholder = %locator%)] | .//label[normalize-space(string(.)) = %locator%]//.//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')]
XPATH
        ,'link' => <<<XPATH
.//a[./@href][(((./@id = %locator% or normalize-space(string(.)) = %locator%) or ./@title = %locator% or ./@rel = %locator%) or .//img[./@alt = %locator%])] | .//*[./@role = 'link'][((./@id = %locator% or ./@value = %locator%) or ./@title = %locator% or normalize-space(string(.)) = %locator%)]
XPATH
        ,'button' => <<<XPATH
.//input[./@type = 'submit' or ./@type = 'image' or ./@type = 'button'][(((./@id = %locator% or ./@name = %locator%) or ./@value = %locator%) or ./@title = %locator%)] | .//input[./@type = 'image'][./@alt = %locator%] | .//button[((((./@id = %locator% or ./@name = %locator%) or ./@value = %locator%) or normalize-space(string(.)) = %locator%) or ./@title = %locator%)] | .//input[./@type = 'image'][./@alt = %locator%] | .//*[./@role = 'button'][(((./@id = %locator% or ./@name = %locator%) or ./@value = %locator%) or ./@title = %locator% or normalize-space(string(.)) = %locator%)]
XPATH
        ,'link_or_button' => <<<XPATH
.//a[./@href][(((./@id = %locator% or normalize-space(string(.)) = %locator%) or ./@title = %locator% or ./@rel = %locator%) or .//img[./@alt = %locator%])] | .//input[./@type = 'submit' or ./@type = 'image' or ./@type = 'button'][((./@id = %locator% or ./@value = %locator%) or ./@title = %locator%)] | .//input[./@type = 'image'][./@alt = %locator%] | .//button[(((./@id = %locator% or ./@value = %locator%) or normalize-space(string(.)) = %locator%) or ./@title = %locator%)] | .//input[./@type = 'image'][./@alt = %locator%] | .//*[(./@role = 'button' or ./@role = 'link')][((./@id = %locator% or ./@value = %locator%) or ./@title = %locator% or normalize-space(string(.)) = %locator%)]
XPATH
        ,'content' => <<<XPATH
./descendant-or-self::*[normalize-space(.) = %locator%]
XPATH
        ,'select' => <<<XPATH
.//select[(((./@id = %locator% or ./@name = %locator%) or ./@id = //label[normalize-space(string(.)) = %locator%]/@for) or ./@placeholder = %locator%)] | .//label[normalize-space(string(.)) = %locator%]//.//select
XPATH
        ,'checkbox' => <<<XPATH
.//input[./@type = 'checkbox'][(((./@id = %locator% or ./@name = %locator%) or ./@id = //label[normalize-space(string(.)) = %locator%]/@for) or ./@placeholder = %locator%)] | .//label[normalize-space(string(.)) = %locator%]//.//input[./@type = 'checkbox']
XPATH
        ,'radio' => <<<XPATH
.//input[./@type = 'radio'][(((./@id = %locator% or ./@name = %locator%) or ./@id = //label[normalize-space(string(.)) = %locator%]/@for) or ./@placeholder = %locator%)] | .//label[normalize-space(string(.)) = %locator%]//.//input[./@type = 'radio']
XPATH
        ,'file' => <<<XPATH
.//input[./@type = 'file'][(((./@id = %locator% or ./@name = %locator%) or ./@id = //label[normalize-space(string(.)) = %locator%]/@for) or ./@placeholder = %locator%)] | .//label[normalize-space(string(.)) = %locator%]//.//input[./@type = 'file']
XPATH
        ,'optgroup' => <<<XPATH
.//optgroup[./@label = %locator%]
XPATH
        ,'option' => <<<XPATH
.//option[(./@value = %locator% or normalize-space(string(.)) = %locator%)]
XPATH
        ,'table' => <<<XPATH
.//table[(./@id = %locator% or .//caption = %locator%)]
XPATH
    );
}
